//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealisasiPinjamanHibahDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PDE2Entities : DbContext
    {
        public PDE2Entities()
            : base("name=PDE2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<VW_REALISASI_DITPH> VW_REALISASI_DITPH { get; set; }
    
        public virtual ObjectResult<USP_GET_DITPH_PAGUVSREAL_BACKUP_Result> USP_GET_DITPH_PAGUVSREAL_BACKUP(string iNSTRUMENT)
        {
            var iNSTRUMENTParameter = iNSTRUMENT != null ?
                new ObjectParameter("INSTRUMENT", iNSTRUMENT) :
                new ObjectParameter("INSTRUMENT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_GET_DITPH_PAGUVSREAL_BACKUP_Result>("USP_GET_DITPH_PAGUVSREAL_BACKUP", iNSTRUMENTParameter);
        }
    
        public virtual ObjectResult<USP_GET_DITPH_PAGUVSREAL_ONGOING_Result> USP_GET_DITPH_PAGUVSREAL_ONGOING(string iNSTRUMENT)
        {
            var iNSTRUMENTParameter = iNSTRUMENT != null ?
                new ObjectParameter("INSTRUMENT", iNSTRUMENT) :
                new ObjectParameter("INSTRUMENT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_GET_DITPH_PAGUVSREAL_ONGOING_Result>("USP_GET_DITPH_PAGUVSREAL_ONGOING", iNSTRUMENTParameter);
        }
    
        public virtual ObjectResult<USP_GET_DITPH_PAGUVSREAL_PIPELINE_Result> USP_GET_DITPH_PAGUVSREAL_PIPELINE(string iNSTRUMENT)
        {
            var iNSTRUMENTParameter = iNSTRUMENT != null ?
                new ObjectParameter("INSTRUMENT", iNSTRUMENT) :
                new ObjectParameter("INSTRUMENT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_GET_DITPH_PAGUVSREAL_PIPELINE_Result>("USP_GET_DITPH_PAGUVSREAL_PIPELINE", iNSTRUMENTParameter);
        }
    
        public virtual ObjectResult<USP_GET_DITPH_PAGUVSREAL_ONGOING_2_Result> USP_GET_DITPH_PAGUVSREAL_ONGOING_2(string iNSTRUMENT, string tANGGAL)
        {
            var iNSTRUMENTParameter = iNSTRUMENT != null ?
                new ObjectParameter("INSTRUMENT", iNSTRUMENT) :
                new ObjectParameter("INSTRUMENT", typeof(string));
    
            var tANGGALParameter = tANGGAL != null ?
                new ObjectParameter("TANGGAL", tANGGAL) :
                new ObjectParameter("TANGGAL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_GET_DITPH_PAGUVSREAL_ONGOING_2_Result>("USP_GET_DITPH_PAGUVSREAL_ONGOING_2", iNSTRUMENTParameter, tANGGALParameter);
        }
    
        public virtual ObjectResult<USP_GET_DITPH_PAGUVSREAL_PIPELINE_2_Result> USP_GET_DITPH_PAGUVSREAL_PIPELINE_2(string iNSTRUMENT, string tANGGAL)
        {
            var iNSTRUMENTParameter = iNSTRUMENT != null ?
                new ObjectParameter("INSTRUMENT", iNSTRUMENT) :
                new ObjectParameter("INSTRUMENT", typeof(string));
    
            var tANGGALParameter = tANGGAL != null ?
                new ObjectParameter("TANGGAL", tANGGAL) :
                new ObjectParameter("TANGGAL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_GET_DITPH_PAGUVSREAL_PIPELINE_2_Result>("USP_GET_DITPH_PAGUVSREAL_PIPELINE_2", iNSTRUMENTParameter, tANGGALParameter);
        }
    }
}
