//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealisasiPinjamanHibahDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_REALISASI_DITPH
    {
        public int NOMOR { get; set; }
        public System.DateTime TANGGAL { get; set; }
        public string KEMENTERIAN { get; set; }
        public string REGISTER { get; set; }
        public string NAMAPROYEK { get; set; }
        public Nullable<decimal> REALISASI { get; set; }
    }
}
